### PR TITLE
Fix audit log file permission and use date suffix in name

### LINKED ISSUE #180: [Bug]: audit.log cannot be opened after second run
### Current Behavior

`audit.log` uses permission value `0000` which will cause permission error next run

### Expected Behavior

audit log shall be opened correctly

### Steps To Reproduce

_No response_

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Resolves #180 
/kind bug

### CODE REVIEW

File: states/instance.go [hunk 1]
```diff
@@ -119,7 +120,8 @@ func (s *InstanceState) DryModeCommand(ctx context.Context, p *DryModeParam) {
 
 func getInstanceState(parent *framework.CmdState, cli clientv3.KV, instanceName, metaPath string, etcdState framework.State, config *configs.Config) framework.State {
 	var kv clientv3.KV
-	file, err := os.OpenFile("audit.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, os.ModeAppend)
+	name := fmt.Sprintf("audit_%s.log", time.Now().Format("2006_0102_150405"))
+	file, err := os.OpenFile(name, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
```
Comment (yah01) [inline states/instance.go:124]: with `O_TRUNC"?
