### PR TITLE
Keep tailing slash for kv operations

### LINKED ISSUE #213: [Bug]: kv returns more entries than wanted
### Current Behavior

Show segment may treat stats log entry as segment 
Get with prefix with tailing '/', this '/' will be ignored

### Expected Behavior

tailing '/' cannot be ignore for kv operations

### Steps To Reproduce

_No response_

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Since `path.Join` will remove tailing slash, the newly added kv implementation will return some other kv values when prefix need this tailing slash.

Add a util function to keep this tailing slash and replace all `path.Join` in kv impl with it

Fix #213

### CODE REVIEW

File: states/kv/utils.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package kv
+
+import (
+	"path"
+	"strings"
+)
+
+func joinPath(parts ...string) string {
+	r := path.Join(parts...)
+	if len(parts) > 0 && strings.HasSuffix(parts[len(parts)-1], "/") {
```
Comment (yah01) [inline states/kv/utils.go:10]: the second condition could be simple:
`strings.HasSuffix(r, "/")`

**Review by yah01 — COMMENTED** [review]
/lgtm

File: states/kv/utils.go (hunk 1 above)
Comment (congqixia) [reply states/kv/utils.go:10]: `r` will never has "/" suffix since path.Join drops the tailing slash
