### PR TITLE
Make force-release work with qcv2 meta

### LINKED ISSUE #136: [Bug]: force release cannot work with 2.2.x milvus
### Current Behavior

force release cannot work with 2.2.x milvus

### Expected Behavior

Force release could handle querycoord v2 meta as well

### Steps To Reproduce

_No response_

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Fix #136 
/kind improvement

### CODE REVIEW

File: states/force_release.go [hunk 1]
```diff
@@ -30,15 +30,20 @@ func getForceReleaseCmd(cli clientv3.KV, basePath string) *cobra.Command {
 					fmt.Printf("backup etcd failed, error: %v, stop doing force-release\n", err)
 				}*/
 
-			// remove all keys start with [basePath]/queryCoord-
-			ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
+			// remove all keys start with [basePath]/queryCoord- qcv1 meta
+			ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
```
Comment (yah01) [inline states/force_release.go:34]: ResourceGroup is a v2 feature, but it starts with "queryCoord"

**Review by yah01 — APPROVED** [review]
/lgtm
